---
title: "04-Finishing/submitting a paper in the lab"
output: html_document
---

# Finishing/submitting a paper in the lab

`lab procedures` `etc`

As I've discussed recently, from now on we need to archive data when a paper is submitted for publication. At a minimum the following is required (and will be updated as we converge on a more established procedure):
1. File the **latest version** of the paper in bioRxiv or most relevant repository and make sure that the lab's website has a link to that version;
2. File all data (fMRI and behavior) in our system (not in a personal account/directory);
3. Archive all data in OpenfMRI or other acceptable public format;
4. File all the processing programs, including versions used;
5. File all illustration figures;
6. File all data figures, including scripts/programs used to generate them. In case the figure involved manual decisions (selection of slices, etc.) this has to be thoroughly documented.

**Item $\textbf{#6}$ is particularly important** and needs executable by someone other than yourself. In a typical case, an RA will work with you on this.

In other words, it no longer suffices to have "all the data backed up". We need to collectively work on this so as to attain better levels of reproducibility: can someone actually reproduce the work that you did?

Finally, not that while before this was encouraged, now it is absolutely mandatory and part of working in the lab. Science is moving fast and we've been lagging behind for too long.
