---
title: "02-Bootstrapping"
output: html_document
---

# Bootstrapping

In the real world, there are many physical and financial constraints on gathering a large data set from a population. Take for example the fMRI, an important tool used to collect brain imaging. It would be wonderful to perform scans on millions upon millions of people to understand brains networks that shed light on how the brain functions. But due to this tool being very expensive, it is unfeasible to scan millions of people. So what do researchers do? Since there is a limited funding, researchers collect data from a small number of people compared to the population. A typical fMRI study includes $30-60$ participants and when we compare this number with $7$ billion people, it is minuscule. When we can only scan about $60$ people, we need a way to infer something about a population from the sample we gathered. This is where bootstrapping comes in.

**Bootstrapping** is re-sampling with replacement from one sample that was gathered from a population. The basic idea is that inference about a population from sample data can be modeled by re-sampling the sample data and performing inference about a sample from re-sampled data. We know nothing about the population because all we have is the sample data.

A good thing about bootstrapping is its incredible simplicity. It is at its core the same thing as **Central limit Theorem**. In Central Limit Theorem, where the means of the multiple samples from a population is plotted on a distribution or sample distribution of sample means. In Bootstrapping, the bootstrap sample is drawn repeatedly with replacement from the original sample. The original sample stands for the population. The mean of these bootstrap samples is plotted, which becomes **bootstrap distribution**.

Let’s take an example that I just made up. We are in a very large field where there could be millions of rabbits. We only have enough resources to catch $10$ rabbits. We go to different areas of the field and randomly catch $10$ rabbits. We want to find the weight of rabbits in kilograms and infer this information onto the population. Our sample, $N = 10$, is distributed in the following fashion $[2, 3, 3, 5, 5, 6, 7, 8, 10, 13]$ in kg. We want to run the bootstrapping technique with this sample. Remember bootstrapping is basically re-sampling with replacement from the original sample. We are not going into the field and catching $10$ more rabbits to find their weight. We only have the weights of the $10$ rabbits we caught in our original sample. So we run a re-sampling with selecting $N$ number of re-samples. We get the following result $[5, 5, 7, 3, 3, 3, 13, 10, 5, 2]$. Let’s call this sample bootstrap sample $1$. The mean of bootstrap sample $1$ is $5.6$. We re-sample again from the original sample and get the following result $[6, 2, 5, 6, 10, 10 ,5, 13, 2, 2]$. Lets call this sample bootstrap sample $2$. The mean of bootstrap sample $2$ is $6.1$. We can see that we are treating the original sample as the new “mini-population”. We can re-sample again and again and get a mean value of $7.1, 4.5, \cdots$ etc. Depending on the computing power we have, we can perform this re-sampling millions of times. We then plot these “bootstrap means” onto a graph and see how the distribution looks like. This distribution of re-sampled means is the bootstrapping distribution. The bootstrapping distribution is used to see whether the sampling distribution is normal rather than hoping that the large sample size we collected is large enough for the central limit theorem to apply.

Bootstrap re-sampling is not a substitution of getting a “good” sample. We can go back to the rabbits example. Lets say that we had not gathered the original sample independently. Instead of randomly selecting rabbits, we had only gone to one burrow and gathered sample from a single burrow which only contained $10$ baby rabbits. The weight data would appear as $[1,1,1,1,1,2,1,1,2,1]$. The mean would be $1.2$. This is not random sampling and we can run as many bootstrapping re-sampling as we want but it will not magically bring us any closer to the population mean weight of rabbits.

***

Posted by Adnan Rashid