---
title: "05-The beauty of programming via probability distributions (and estimating them)"
output: html_document
---


# The beauty of programming via probability distributions (and estimating them)

What does the title even mean?

Say you encountered this in a statistics text:
$$ x \sim N(0, 1) $$
which just says that the random variable $x$ is normally distributed with $0$ mean and variance $1$. If you write that in your program, $x$ will automatically be distributed that way and draws from that distribution will be drawn when $x$ is needed **elsewhere**.

Here's a more complex model:
$$ z_{lk} = p_{l} + \epsilon_{l, k}, k = 1, 2, \cdots, n $$
This is ugly, but ${lk}$ and ${l}$ are just subscripts, that is, indeces. What does this mean? The varible $z$ is estimated as an **additive** contribution of a population effect of the variable that you are interested in $p$ (for example, the experimental condition that you manipulated $l$; "ell") and $\epsilon_{lk}$ is the deviation (or effect) of subject $k$ on condition $l$.

What does this mean? If you know what the Stroop effect is: $p_l$ could be the contribution (effect) of an incongruent condition. And $\epsilon_{l,k}$ the contribution (effect) of subject $k$, that is, sort of the average response time across all conditions for that person (if I'm fast in general, or slow in general). So what the experimental condition (incongruent trials) does is a **deviation** from my average reaction time based on the condition.

By including both a **fixed effect p** (the conditions of your experiment; they are fixed, right?) and the **random effect** (the one that you draw randomly), that is, participants, you have a **mixed-effcts model** And you're done! Or not far from it actually (so close that it's scary).

If you don't know what the Stroop effect is, it doesn't matter (but look it up). The model is general and that's what math is for, right?

Well, this was a little longer than I thought.